import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 3,
    borderBottomColor: '#e2c0d7',
    paddingBottom: 15,
  },
  logo: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 5,
    letterSpacing: 2,
  },
  tagline: {
    fontSize: 12,
    color: '#666666',
    fontStyle: 'italic',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#000000',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#e2c0d7',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  content: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#333333',
  },
  h2: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 8,
    color: '#000000',
  },
  h3: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 12,
    marginBottom: 6,
    color: '#333333',
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#333333',
    marginBottom: 8,
  },
  listItem: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#333333',
    marginBottom: 4,
    paddingLeft: 15,
  },
  bold: {
    fontWeight: 'bold',
  },
  venueItem: {
    marginBottom: 15,
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#e2c0d7',
  },
  venueName: {
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#000000',
  },
  venueDetails: {
    fontSize: 10,
    color: '#666666',
    marginBottom: 2,
  },
  timeline: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#f9f9f9',
    borderRadius: 4,
  },
  timelineItem: {
    fontSize: 11,
    marginBottom: 6,
    color: '#333333',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: '#e2c0d7',
    paddingTop: 10,
    fontSize: 9,
    color: '#999999',
    textAlign: 'center',
  },
  emoji: {
    fontSize: 14,
  },
  highlight: {
    backgroundColor: '#f5e6f0',
    padding: 10,
    marginBottom: 15,
    borderRadius: 4,
  },
  highlightText: {
    fontSize: 11,
    color: '#333333',
    fontStyle: 'italic',
  },
});

interface DatePlanPDFProps {
  dateName: string;
  content: string;
  userName?: string;
  generatedDate?: string;
}

// Strip emojis, markdown formatting, and other unsupported characters
function stripForPdf(text: string): string {
  return text
    // Strip markdown bold/italic
    .replace(/\*\*(.+?)\*\*/g, '$1')  // **bold** -> bold
    .replace(/\*(.+?)\*/g, '$1')       // *italic* -> italic
    .replace(/_(.+?)_/g, '$1')         // _italic_ -> italic
    .replace(/`(.+?)`/g, '$1')         // `code` -> code
    // Strip emojis
    .replace(/[\u{1F600}-\u{1F6FF}]/gu, '')
    .replace(/[\u{1F300}-\u{1F5FF}]/gu, '')
    .replace(/[\u{1F680}-\u{1F6FF}]/gu, '')
    .replace(/[\u{1F700}-\u{1F77F}]/gu, '')
    .replace(/[\u{1F780}-\u{1F7FF}]/gu, '')
    .replace(/[\u{1F800}-\u{1F8FF}]/gu, '')
    .replace(/[\u{1F900}-\u{1F9FF}]/gu, '')
    .replace(/[\u{1FA00}-\u{1FA6F}]/gu, '')
    .replace(/[\u{1FA70}-\u{1FAFF}]/gu, '')
    .replace(/[\u{2300}-\u{23FF}]/gu, '')
    .replace(/[\u{2600}-\u{26FF}]/gu, '')
    .replace(/[\u{2700}-\u{27BF}]/gu, '')
    .replace(/[\u{FE00}-\u{FE0F}]/gu, '')
    .replace(/[\u{1F000}-\u{1F02F}]/gu, '')
    .replace(/[\u{1F0A0}-\u{1F0FF}]/gu, '')
    .replace(/[\u{200D}]/gu, '')
    .trim();
}

export const DatePlanPDF: React.FC<DatePlanPDFProps> = ({
  dateName,
  content,
  userName,
  generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }),
}) => {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header with Logo */}
        <View style={styles.header}>
          <Text style={styles.logo}>WINGMAN</Text>
          <Text style={styles.tagline}>Your AI Dating Assistant</Text>
        </View>

        {/* Date Plan Title */}
        <Text style={styles.title}>{dateName}</Text>

        {/* User Info */}
        {userName && (
          <View style={styles.highlight}>
            <Text style={styles.highlightText}>
              Personalized for {userName} - {generatedDate}
            </Text>
          </View>
        )}

        {/* Main Content */}
        <View style={styles.section}>
          {renderMarkdown(stripForPdf(content))}
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>
            Generated by wingMan - AI-Powered Date Planner - {generatedDate}
          </Text>
          <Text style={{ marginTop: 4 }}>
            Remember: Be yourself and have fun!
          </Text>
        </View>
      </Page>
    </Document>
  );
};

// Render markdown content as React-PDF components
function renderMarkdown(content: string): React.ReactNode[] {
  const lines = content.split('\n');
  const elements: React.ReactNode[] = [];
  let key = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Skip empty lines
    if (!trimmed) {
      continue;
    }

    // H2 headers (##)
    if (trimmed.startsWith('## ')) {
      elements.push(
        <Text key={key++} style={styles.h2}>
          {trimmed.replace(/^##\s*/, '')}
        </Text>
      );
    }
    // H3 headers (###)
    else if (trimmed.startsWith('### ')) {
      elements.push(
        <Text key={key++} style={styles.h3}>
          {trimmed.replace(/^###\s*/, '')}
        </Text>
      );
    }
    // H1 headers (#)
    else if (trimmed.startsWith('# ')) {
      elements.push(
        <Text key={key++} style={styles.h2}>
          {trimmed.replace(/^#\s*/, '')}
        </Text>
      );
    }
    // Bullet points (- or *)
    else if (trimmed.match(/^[-*]\s/)) {
      const bulletContent = trimmed.replace(/^[-*]\s*/, '');
      elements.push(
        <Text key={key++} style={styles.listItem}>
          • {bulletContent}
        </Text>
      );
    }
    // Numbered lists
    else if (trimmed.match(/^\d+\.\s/)) {
      const num = trimmed.match(/^(\d+)\./)?.[1];
      const listContent = trimmed.replace(/^\d+\.\s*/, '');
      elements.push(
        <Text key={key++} style={styles.listItem}>
          {num}. {listContent}
        </Text>
      );
    }
    // Regular paragraph
    else {
      elements.push(
        <Text key={key++} style={styles.paragraph}>
          {trimmed}
        </Text>
      );
    }
  }

  return elements;
}
