import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 3,
    borderBottomColor: '#e2c0d7',
    paddingBottom: 15,
  },
  logo: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 5,
    letterSpacing: 2,
  },
  tagline: {
    fontSize: 12,
    color: '#666666',
    fontStyle: 'italic',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#000000',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#e2c0d7',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  content: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#333333',
  },
  venueItem: {
    marginBottom: 15,
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#e2c0d7',
  },
  venueName: {
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#000000',
  },
  venueDetails: {
    fontSize: 10,
    color: '#666666',
    marginBottom: 2,
  },
  timeline: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#f9f9f9',
    borderRadius: 4,
  },
  timelineItem: {
    fontSize: 11,
    marginBottom: 6,
    color: '#333333',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: '#e2c0d7',
    paddingTop: 10,
    fontSize: 9,
    color: '#999999',
    textAlign: 'center',
  },
  emoji: {
    fontSize: 14,
  },
  highlight: {
    backgroundColor: '#f5e6f0',
    padding: 10,
    marginBottom: 15,
    borderRadius: 4,
  },
  highlightText: {
    fontSize: 11,
    color: '#333333',
    fontStyle: 'italic',
  },
});

interface DatePlanPDFProps {
  dateName: string;
  content: string;
  userName?: string;
  generatedDate?: string;
}

export const DatePlanPDF: React.FC<DatePlanPDFProps> = ({
  dateName,
  content,
  userName,
  generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }),
}) => {
  // Parse the AI response to extract structured information
  const sections = parseContent(content);

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header with Logo */}
        <View style={styles.header}>
          <Text style={styles.logo}>WINGMAN</Text>
          <Text style={styles.tagline}>Your AI Dating Assistant</Text>
        </View>

        {/* Date Plan Title */}
        <Text style={styles.title}>{dateName}</Text>

        {/* User Info */}
        {userName && (
          <View style={styles.highlight}>
            <Text style={styles.highlightText}>
              💝 Personalized for {userName} • {generatedDate}
            </Text>
          </View>
        )}

        {/* Main Content */}
        <View style={styles.section}>
          <Text style={styles.content}>{content}</Text>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>
            Generated by wingMan • AI-Powered Date Planning • {generatedDate}
          </Text>
          <Text style={{ marginTop: 4 }}>
            Remember: Be yourself and have fun! 💕
          </Text>
        </View>
      </Page>
    </Document>
  );
};

// Helper function to parse content (can be enhanced)
function parseContent(content: string) {
  const sections: Array<{ title: string; content: string }> = [];

  // Simple parsing - can be enhanced based on AI response format
  const lines = content.split('\n');
  let currentSection = { title: '', content: '' };

  lines.forEach((line) => {
    if (line.match(/^#{1,3}\s/)) {
      if (currentSection.title) {
        sections.push(currentSection);
      }
      currentSection = { title: line.replace(/^#{1,3}\s/, ''), content: '' };
    } else if (line.trim()) {
      currentSection.content += line + '\n';
    }
  });

  if (currentSection.title) {
    sections.push(currentSection);
  }

  return sections;
}
